VOWELS [AaEeIiOoUuYy]
%%

({VOWELS}*[Zz]*)*({VOWELS}*[Xx]*)*({VOWELS}*[Ww]*)*({VOWELS}*[Vv]*)*({VOWELS}*[Tt]*)*({VOWELS}*[Ss]*)*({VOWELS}*[Rr]*)({VOWELS}*[Qq]*)*({VOWELS}*[Pp]*)*({VOWELS}*[Nn]*)*({VOWELS}*[Nn]*)*({VOWELS}*[Mm]*)*({VOWELS}*[Ll]*)*({VOWELS}*[Kk]*)*({VOWELS}*[Jj]*)*({VOWELS}*[Hh]*)*({VOWELS}*[Gg]*)*({VOWELS}*[Ff]*)*({VOWELS}*[Dd]*)*({VOWELS}*[Cc]*)*({VOWELS}*[Bb]*)*{VOWELS}* ECHO; putchar('\n');

[^" "\n\t]*[A-Za-z]+[^" "\n\t]* ;


.|\n ;
